version: '3'
services:
    db:
        image: mysql:5.7
        networks:
            - chassis
        volumes:
            - "db-data:/var/lib/mysql"
        ports:
            - "3306:3306"
        env_file:
            - config.env
    php:
        image: chassis
        build: .
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
volumes:
    db-data:
networks:
    chassis:
