version: '3'
services:
    db:
        image: mysql:5.7
        volumes:
            - "db-data:/var/lib/mysql"
        ports:
            - "3306:3306"
        networks:
            - chassis
        env_file:
            - config.env
    nginx:
        image: nginx:latest
        expose:
            - "80"
            - "443"
        volumes:
            - "./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
            - "./config/nginx/site.nginx.conf:/etc/nginx/conf.d/site.nginx.conf"
        networks:
            - chassis
        env_file:
            - config.env
        depends_on:
            - php
    php:
        depends_on:
          - db
        image: chassis
        build: .
        ports:
            - "80:80"
        volumes:
            - "./content:/var/www/html/wp-content"
            - "./content/themes:/var/www/html/wp-content/themes"
            - "./content/plugins:/var/www/html/wp-content/plugins"
            - "./content/mu-plugins:/var/www/html/wp-content/mu-plugins"
        networks:
            - chassis
        env_file:
            - config.env
    mailhog:
        image: mailhog/mailhog
        ports:
            - "1025:1025"
            - "8025:8025"
        networks:
            - chassis
volumes:
    db-data:
networks:
    chassis:
