version: '3'
services:
    db:
        image: mysql:5.7
        networks:
            - chassis
        volumes:
            - "db-data:/var/lib/mysql"
        ports:
            - "3306:3306"
        env_file:
            - config.env
    php:
        depends_on:
          - db
        image: chassis
        build: .
        ports:
            - "80:80"
        volumes:
            - "./content:/var/www/html/wordpress/wp-content"
        networks:
            - chassis
        env_file:
            - config.env
volumes:
    db-data:
networks:
    chassis:
